// <auto-generated />
using System;
using Catalog.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DALContext))]
    [Migration("20251212162104_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.DAL.Entities.MedicalCheckup", b =>
                {
                    b.Property<int>("checkupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("conclusion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("recordId")
                        .HasColumnType("int");

                    b.HasKey("checkupId");

                    b.HasIndex("recordId");

                    b.ToTable("MedicalCheckups");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("recordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("deseaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("history")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastCheckup")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("recordId");

                    b.HasIndex("employeeId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.Notification", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeuserId")
                        .HasColumnType("int");

                    b.Property<bool>("available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("scheduleId")
                        .HasColumnType("int");

                    b.HasKey("notificationId");

                    b.HasIndex("EmployeeuserId");

                    b.HasIndex("doctorId");

                    b.HasIndex("scheduleId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.Report", b =>
                {
                    b.Property<int>("reportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("generatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("reportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.Schedule", b =>
                {
                    b.Property<int>("scheduledId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.HasKey("scheduledId");

                    b.HasIndex("doctorId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.Admin", b =>
                {
                    b.HasBaseType("Catalog.DAL.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.Employee", b =>
                {
                    b.HasBaseType("Catalog.DAL.Entities.User");

                    b.Property<string>("department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("position")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.MedicalStaff", b =>
                {
                    b.HasBaseType("Catalog.DAL.Entities.User");

                    b.Property<string>("position")
                        .HasColumnName("MedicalStaff_position")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MedicalStaff");
                });

            modelBuilder.Entity("Catalog.DAL.Entities.MedicalCheckup", b =>
                {
                    b.HasOne("Catalog.DAL.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("MedicalCheckups")
                        .HasForeignKey("recordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Catalog.DAL.Entities.MedicalRecord", b =>
                {
                    b.HasOne("Catalog.DAL.Entities.Employee", "Employee")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.DAL.Entities.Notification", b =>
                {
                    b.HasOne("Catalog.DAL.Entities.Employee", null)
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeuserId");

                    b.HasOne("Catalog.DAL.Entities.MedicalStaff", "Doctor")
                        .WithMany("Notifications")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catalog.DAL.Entities.Schedule", "Schedule")
                        .WithMany("Notifications")
                        .HasForeignKey("scheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Catalog.DAL.Entities.Schedule", b =>
                {
                    b.HasOne("Catalog.DAL.Entities.MedicalStaff", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
